### ISSUE TITLE
유저정보 수정 화면 텍스트 오타

### ISSUE THREAD

**Issue by PCYSB** [imad-project/imad-ios#104]
유저정보 수정 화면의 4 번째 화면에서 "2. 관심있는 장르를 선택해 주세요"에서 2. 을 없애야 한다.

**Comment by QuaRang1225** [comment]
또한 화면을 나갔다 들어오면 설정한 출생연도값이 계속 초기값으로 바뀌는 문제도 존재

**Comment by QuaRang1225** [comment]
수정완
