### ISSUE TITLE
20231014 ios 앱 피드백

### ISSUE THREAD

**Issue by NCookies** [imad-project/imad-ios#39]
- 회원가입 이후 프로필 설정할 때 장르가 선택되지 않음
- 리뷰 작성 시 [~님의 평점]에서 ~가 콰쾅으로 고정되어 있음(닉네임이 적용되지 않음)
- 같은 작품에 리뷰를 2개 이상 작성하려고 할 때 수정화면으로 이동해야 함(현재는 경고 팝업만 뜸)
- [내 리뷰]와 [리뷰 보기]가 구분이 잘 되지 않음

**Comment by QuaRang1225** [comment]
확인

**Comment by QuaRang1225** [comment]
- 회원가입 이후 프로필 설정할 때 장르가 선택되지 않음
-> 메서드 매개변수 추가
- 리뷰 작성 시 [~님의 평점]에서 ~가 콰쾅으로 고정되어 있음(닉네임이 적용되지 않음)
-> 상수 변수로 변환
- 같은 작품에 리뷰를 2개 이상 작성하려고 할 때 수정화면으로 이동해야 함(현재는 경고 팝업만 뜸)
-> 팝업 확인 버튼 후 dimiss 메서드 추가
- [내 리뷰]와 [리뷰 보기]가 구분이 잘 되지 않음
-> 디자인 변경
