### ISSUE TITLE
20231028 ios 앱 피드백

### ISSUE THREAD

**Issue by NCookies** [imad-project/imad-ios#55]
### 불편사항
- [x] 일반회원 회원가입 직후 자동으로 로그인이 되지 않음
- [x] 최초 로그인 후 회원설정 할 때 장르가 선택되지 않음 (아이패드)
- [x] 리뷰 작성 시 점수 그림과 배경 색깔이 구분되지 않음

### 요구사항
- [x] 커뮤니티 작성 버튼 추가
- [x] 리뷰 중복 작성 시 기존의 작성하던 내용을 불러와서 수정화면을 보여줬으면 함
- [x] 리뷰나 게시글에서 작품을 터치했을 때 해당 작품의 상세정보 화면으로 이동했으면 함
- [ ] 게시글 작성 후 커뮤니티 또는 작성한 게시글 화면으로 이동

**Comment by QuaRang1225** [comment]
### 불편사항
- 일반회원 회원가입 직후 자동으로 로그인이 되지 않음
 -> 회원가입 직후 로그인 요청 
- 최초 로그인 후 회원설정 할 때 장르가 선택되지 않음 (아이패드)
 -> 어플에서 문제가 갑작스레 해결됨. 그냥 단순 버그였던것으로 추정. 시간을 두고 확인해볼 필요가 있음
- 리뷰 작성 시 점수 그림과 배경 색깔이 구분되지 않음
 -> 규격 변경(추가사항 참고)
### 요구사항
- 커뮤니티 작성 버튼 추가 요망
 -> 커뮤니티 메뉴탭 확인
![image](https://github.com/imad-project/imad-ios/assets/31721255/fdd02c81-4377-464d-afae-de07033282f8)

- 리뷰 중복 작성 시 기존의 작성하던 내용을 불러와서 수정화면을 보여줬으면 함
 -> 작품에 본인 작성 리뷰가 있을 경우 강제로 리뷰작성을 못하도록 하는 기능 추가
- 리뷰나 게시글에서 작품을 터치했을 때 해당 작품의 상세정보 화면으로 이동했으면 함
 -> 기능 추가
### 추가사항
 - 아이패드 호환가능 (전체적으로 아이패드 규격에 맞춰짐)

**Comment by NCookies** [comment]
- 아이패드 호환이 되도록 업데이트한 이후, 이전과 마찬가지로 회원가입 시 장르가 선택되지 않음
- 게시글 작성 이후 화면 이동

자세한 내용은 이슈 본문 참고

**Comment by QuaRang1225** [comment]
- 아이패드 호환이 되도록 업데이트한 이후, 이전과 마찬가지로 회원가입 시 장르가 선택되지 않음
 -> 이전 코드에서 영화,TV장르가 비어있을 경우를 제외한 조건을 전재로 버튼이벤트가 생겼었음(배열이 null일때는 버튼 동작을 안하고 배열이 존재는 하지만 []일때만 장르 추가가 가능했었음) 
-> 사실 아이패드도 아이폰도 모두 작동 안했었음

- 게시글 작성 이후 화면 이동
 -> 네비게이션 뷰 이벤트 추가
