### ISSUE TITLE
신고하기/문의하기 기능 추가

### ISSUE THREAD

**Issue by QuaRang1225** [imad-project/imad-ios#82]
우선순위가 높은 건 아니지만 커뮤니티 특성상 신고 기능이 필요하다고 판단됨
ex) 선정성,폭력성,정치성 등

> 신고가 필요한 기능
- 유저정보
- 게시물
- 리뷰
- 댓/답글

추가적으로 작품정보 수정 및 작품 등록 요청도 필요하다고 판단
- 가능여부를 혼자 판단 불가하여 추가 회의 필요

**Comment by NCookies** [comment]
- 관련 내용은 관리자 페이지와 함께 구현될 예정임
- 관리자 페이지는 정식 버전 릴리즈 후 업데이트될 예정

**Comment by QuaRang1225** [comment]
zz
