### ISSUE TITLE
회원가입 시 이메일 및 닉네임 중복 검사 관련 잇슈

### ISSUE THREAD

**Issue by QuaRang1225** [imad-project/imad-ios#87]
### 현재 문제 

- 이메일 및 닉네임 중복확인 후 이메일 수정한뒤 중복확인 버튼을 누르지 않고 회원가입 시 회원가입이 되는 문제 발생
- 원래는 중복확인이 무조건 된 상태에서만 회원가입이 되도록 허용해야함

###  해결방안 
- 메서드에 예외처리를 추가하도록함
  1. 변수 두개를 선언 (TextField의 상태변수 A,중복확인 시 이메일을 저장해둘 변수B)
  2. 이메일 작성 후 중복확인을 터치할 시 B변수에 값을 저장
  3. 회원가입 시 A와 B의 문자열을 비교하여 같을 시 회원가입 메서드 호출

**Comment by PCYSB** [comment]
확인
