### ISSUE TITLE
게시물/리뷰 작성 시 문자열 글자수 제한

### ISSUE THREAD

**Issue by QuaRang1225** [imad-project/imad-ios#89]
### 현재 문제

- 게시물과 리뷰 작성 시 문자열크기(256btyes)를 넘길 시 요청이 실패되는 문제 발생
- 리뷰/커뮤니티 특성상 긴 글을 작성해야함으로 타격이 클것이라 판단
- 현재 문제에 대해서 주도면밀히 회의할 필요가 있음

**Comment by NCookies** [comment]
https://github.com/imad-project/imad-server/wiki/%EA%B8%80%EC%9E%90%EC%88%98-%EC%A0%9C%ED%95%9C

**Comment by NCookies** [comment]
3adcf17 커밋 참고

**Comment by QuaRang1225** [comment]
[해당잇슈](https://github.com/imad-project/imad-server/wiki/%EA%B8%80%EC%9E%90%EC%88%98-%EC%A0%9C%ED%95%9C)를 참고함

- 리뷰/게시물 제목 본문(25글자)
- 리뷰/게시물 본문(2500글자)
- 댓글 (400글자)
